/*
 * LibraryManagementAPI
 * LibraryManagementAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Payload;
import io.swagger.client.model.Payload1;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void borrowerBorrowerIdDeleteTest() throws ApiException {
        String borrowerId = null;
        api.borrowerBorrowerIdDelete(borrowerId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void borrowerBorrowerIdGetTest() throws ApiException {
        String borrowerId = null;
        api.borrowerBorrowerIdGet(borrowerId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void borrowerGetTest() throws ApiException {
        api.borrowerGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void borrowerPostTest() throws ApiException {
        Payload1 payload = null;
        api.borrowerPost(payload);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void borrowerPutTest() throws ApiException {
        Payload payload = null;
        api.borrowerPut(payload);

        // TODO: test validations
    }
    
}
